### ISSUE TITLE
Numbers from table in presentation - header missing?

### ISSUE THREAD

**Issue by vladimirkovacevic** [kilibardajovica/gi-project#2]
![Screen Shot 2020-04-27 at 23 50 22](https://user-images.githubusercontent.com/16796045/80425113-4ed8b480-88e3-11ea-8f82-ac128192fe68.png)
If the numbers given here are probabilities then the accuracy is unexpectedly low? How was it measured?

**Comment by kilibardajovica** [comment]
Numbers are probability values for certain type of mutation. Accuracy was measured as with every other genome, comparing output SAM file from simulator and the one from BWA-MEM.  I noticed, that without mutations, accuracy is lower than for the other genomes I analyzed, but after running it multiple times I got the same results. As for the last two columns accuracy is low, because even these little probabilities result in large numbers of mutations.

**Comment by vladimirkovacevic** [comment]
So, for example, probability 0.01 for DEL and INS means one deletion and insertion (what is the size of deletion/insertion?) will be added on every 100 nucleotides? So, every read has on average one INS one DEL, degrading the accuracy from 95.2% to 4.8%?

**Comment by kilibardajovica** [comment]
Insertion and deletion sizes are one nucleotide, so yes, on average, every read will have one insertion and one deletion.

**Comment by vladimirkovacevic** [comment]
OK, I see. Well, I wasn't expecting result like this, but OK, numbers do not lie :)
